#!/bin/bash

# Script to make the PGPLOT libraries.
# Exit Codes found in /usr/include/sysexits.h

#set -x


# Function to configure, make and then install the Package - contains Package Specific build configuration

func_configure_make_install () {

    cd ${WORK_DIR}

    if [ ! -e ALREADY_BUILT ] ; then
	rm -f libpgplot.a
	rm -f libpgplot.so
	rm -f libcpgplot.a
	rm -f cpgdemo
	rm -f figdisp
	rm -f pgdisp
	rm -f pgxwin_server
    
	if [[ $ACC_COMPILER_TOOLSET == mingw* ]]; then
		SPEC=gfortran-gcc
		OS=win7
	else
		SPEC=${FC}_gcc
		OS=linux
	fi
    
	[ "${FC}" == "ifort" ] && export NON_FORTRAN_MAIN_LINK="-nofor_main"
	[ "${BUILD_TYPE}" == "debug" ] && SPEC+='_g'

	if ( [ ! -d /usr/X11R6/include ] && [ `uname` == "Linux" ] && [ "${FC}" == "gfortran" ] ) ; then
	    [ -d /usr/include/X11 ] && sed -i "s%usr/X11R6/include%usr/include%g" sys_linux/gfortran_gcc*.conf
 	    [ -e /usr/lib64/libX11.so ] && sed -i "s%usr/X11R6/lib%usr/lib64%g" sys_linux/gfortran_gcc*.conf
	fi

	if [ `uname` == "Darwin" ] ; then 
	    OS=bsd
	    export CC="g++"
	    [ "${FC}" == "ifort" ] && export DYLD_LIBRARY_PATH="/opt/intel/lib:$DYLD_LIBRARY_PATH"
	    [ -d /opt/X11 ] && sed -i .old "s%usr/X11R6%opt/X11%g" sys_bsd/*.conf || echo -e "\nPlease install XQuartz - http://xquartz.macosforge.org/landing/ \n"
	fi

	echo -e "\nmakemake args: ${OS} ${SPEC}\n"
	./makemake . ${OS} ${SPEC}

	func_print_compiler_linker_flags

	${GMAKE}
	${GMAKE} cpg

	export RETVAL=$?

	[ ! -e ${OUTPUT_DIR}/lib/libpgplot.a ] && cp libpgplot.a ${OUTPUT_DIR}/lib && ln -s ../${BUILD_TYPE}/lib/libpgplot.a ../libpgplot.a > /dev/null 2>&1
	[ ! -e ${OUTPUT_DIR}/lib/llibpgplot.so ] && cp libpgplot.so ${OUTPUT_DIR}/lib > /dev/null 2>&1 && ln -s ../${BUILD_TYPE}/lib/libpgplot.so ../libpgplot.so > /dev/null 2>&1
	[ ! -e ${OUTPUT_DIR}/lib/libcpgplot.a ] && cp libcpgplot.a ${OUTPUT_DIR}/lib && ln -s ../${BUILD_TYPE}/lib/libcpgplot.a ../libcpgplot.a > /dev/null 2>&1
	[ ! -e ${OUTPUT_DIR}/bin/cpgdemo ] && cp cpgdemo ${OUTPUT_DIR}/bin && ln -s ../${BUILD_TYPE}/bin/cpgdemo ../cpgdemo > /dev/null 2>&1
	[ ! -e ${OUTPUT_DIR}/bin/pgdisp ] && cp pgdisp ${OUTPUT_DIR}/bin && ln -s ../${BUILD_TYPE}/bin/pgdisp ../pgdisp > /dev/null 2>&1 && ln -s ../${BUILD_TYPE}/bin/pgdisp ../figdisp > /dev/null 2>&1
	[ ! -e ${OUTPUT_DIR}/bin/pgxwin_server ] && cp pgxwin_server ${OUTPUT_DIR}/bin  && ln -s ../${BUILD_TYPE}/bin/pgxwin_server ../pgxwin_server > /dev/null 2>&1

	if ( [ `uname` == "Darwin" ] && [ "${FC}" == "ifort" ] && [ "${RETVAL}" -eq 0 ] ) ; then ln -s /opt/intel/lib/* ${OUTPUT_DIR}/lib/ > /dev/null 2>&1 ; fi

	[ -e pgplot_mod.mod ] && cp pgplot_mod.mod ${OUTPUT_DIR}/modules

    fi

    if [ "${ARGUMENTS[1]}" == "-test" ] ; then 
	echo -e "\nBuilding tests for `echo ${PACKAGE_VERSION}`...\n" 
	PATH=${OUTPUT_DIR}/bin:$PATH
	LD_LIBRARY_PATH=${OUTPUT_DIR}/lib:$LD_LIBRARY_PATH
	PGPLOT_DIR=${WORK_DIR}
	echo "/CPS" | cpgdemo > /dev/null 2>&1
	export RETVAL=$?
	[ ${RETVAL} -eq 0 ] && echo -e "\nTest Passed!! \n\nPlease display the below output file in a Postscript viewer:\n\n   ${WORK_DIR}/pgplot.ps\n" || echo -e "\nTests Failed, Please check build log.\n"

    fi

}


# Function that contains Package Specific files and directories to be removed

func_remove_package () {

    rm -f ${OUTPUT_DIR}/lib/libpgplot.a 
    rm -f ${OUTPUT_DIR}/lib/libpgplot.so
    rm -f ${OUTPUT_DIR}/lib/libcpgplot.a
    rm -f ${OUTPUT_DIR}/bin/cpgdemo
    rm -f ${OUTPUT_DIR}/bin/pgdisp
    rm -f ${OUTPUT_DIR}/bin/pgxwin_server
    rm -f ${OUTPUT_DIR}/modules/pgplot_mod.mod
    rm -rf ${BUILD_TYPE}
    if ( [ -L libpgplot.a ] && [ "`ls -la libpgplot.a | grep ${BUILD_TYPE}`" ] ) ; then rm -f libpgplot.a > /dev/null 2>&1 ; fi 
    if ( [ -L libpgplot.so ] && [ "`ls -la libpgplot.so | grep ${BUILD_TYPE}`" ] ) ; then rm -f libpgplot.so > /dev/null 2>&1 ; fi
    if ( [ -L libcpgplot.a ] && [ "`ls -la libcpgplot.a | grep ${BUILD_TYPE}`" ] ) ; then rm -f libcpgplot.a > /dev/null 2>&1 ; fi
    if ( [ -L cpgdemo ] && [ "`ls -la cpgdemo | grep ${BUILD_TYPE}`" ] ) ; then rm -f cpgdemo > /dev/null 2>&1 ; fi 
    if ( [ -L pgdisp ] && [ "`ls -la pgdisp | grep ${BUILD_TYPE}`" ] ) ; then rm -f pgdisp figdisp > /dev/null 2>&1 ; fi 
    if ( [ -L pgxwin_server ] && [ "`ls -la pgxwin_server | grep ${BUILD_TYPE}`" ] ) ; then rm -f pgxwin_server > /dev/null 2>&1 ; fi

    rm -f ${BASE_DIR}/${PROJ_DIR_NAME}/figdisp
    rm -f ${BASE_DIR}/${PROJ_DIR_NAME}/cpgdemo

}

