/* GDF Error handling: Header file generated by ../../utils/makeerr/makeerr */

#define GDFERR_FE 0
#define GDFERR_NEM 1
#define GDFERR_UEF 2
#define GDFERR_IDF 3
#define GDFERR_IDV 4
#define GDFERR_IMD 5
#define GDFERR_IDT 6
#define GDFERR_IMDT 7
#define GDFERR_INO 8
#define GDFERR_CANDA 9
#define GDFERR_ISTTY 10
